version: 2

project_name: gridist

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
  - env:
      # ARM64
      - CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
      - CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
      # macOS
      - CC_aarch64_apple_darwin=clang
      - CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=clang

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

# Creates Darwin universal binaries.
universal_binaries:
  - replace: true

# Creates Linux packages.
nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    maintainer: kiwamizamurai
    formats:
      - deb
      - apk
      - rpm

# Enables source archives.
source:
  enabled: true

# SBOMs for the archives.
sboms:
  - artifacts: archive

# Sign binaries with cosign.
signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

brews:
  - repository:
      owner: kiwamizamurai
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    directory: Formula
    homepage: https://github.com/kiwamizamurai/gridist
    description: A powerful cli tool that transforms your images into eye-catching grid layouts for your GitHub profile
    license: MIT
    test: |
      system "#{bin}/gridist --version"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).