[tools]
rust = "1.79"

[tasks.build]
run = ["cargo build"]

[tasks.fmt]
run = ["cargo fmt --all"]

[tasks.lint]
run = [
    "cargo clippy -- -D warnings",
    "cargo fmt --all -- --check"
]

[tasks.test]
run = ["cargo test --verbose"]